apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/lcarva/golden-container?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
    pipelinesascode.tekton.dev/pipeline: ".tekton/build-pipeline.yaml"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: golden-container
    appstudio.openshift.io/component: golden-container
    pipelines.appstudio.openshift.io/type: build
  name: golden-container-on-push
  namespace: lucarval-tenant
spec:
  params:
  - name: dockerfile
    value: Containerfile
  - name: git-url
    value: '{{repo_url}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/lucarval-tenant/golden-container/golden-container:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: hermetic
    value: 'true'
  - name: build-source-image
    value: 'true'
  pipelineRef:
    name: build
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
